### ISSUE TITLE
In zsh and with the new version, it keeps asking about correcting perl6 to perl

### ISSUE THREAD

**Issue by JJ** [tadzik/rakudobrew#141] opened 2019-05-14 15:51 UTC
Apparently, shell functions have a lower priority (or whatever) than commands. 
Fix:

```
alias perl6='nocorrect perl6'
```

**Comment by patzim** [comment] 2019-06-01 15:18
Disclamer: My zsh knowledge is very limited.
I don't understand this behavior. Rakudobrew does not install any shell function called `perl6`.  Are you sure this is related to rakudobrew? Also I can't reproduce this. Any hints on what I need to do to reproduce are welcome.

**Comment by JJ** [comment] 2019-06-01 18:23
I don't understand that either, but it's what happened... I just followed the standard procedure to install.

**Comment by patzim** [comment] 2019-06-02 19:29
@JJ I'd be grateful if you could do some investigation yourself. I'm pretty lost here, as I can't reproduce the symptom and am also quite unknowledgable of zsh. For a start I'd check if the strange behavior also appears when you start a shell without the rakudo init code.

**Comment by avuserow** [comment] 2019-06-09 04:39
@patzim I'm able to replicate this on my system (Fedora 30). This seems to be caused by the `..` within the PATH generated by rakudobrew. If I run `rakudobrew init Zsh` and copy the resulting output into my zshrc, then I can fix this problem by removing the `bin/..` part of the path.

It looks like we just need to do the P5 equivalent of .resolve on the paths we put into $PATH.

Let me know if I can provide any more information on this.

**Comment by patzim** [comment] 2019-06-17 22:22
I just pushed [a change](https://github.com/tadzik/rakudobrew/commit/6f9f11f19156941fc7291da3ea1be6f36698bbd4) that strips `..` from the paths.

I am still not able to repoduce this on my computer.
@avuserow, @JJ can you test this?

**Comment by avuserow** [comment] 2019-06-21 00:36
Looks good to me.

I updated my .zshrc to use `rakudobrew init Zsh` rather than my manual copy/pasted workaround earlier and now it works.

As for why this is only on some machines, maybe this is a recent change in zsh? I've used rakudobrew off and on previously on different linux distros and I'm currently only seeing this on Fedora 30.

Thanks for the fix! :+1:

**Comment by patzim** [comment] 2019-06-24 10:28
Sounds good! Closing.

**Closed by patzim** 2019-06-24 10:28 UTC

**Comment by JJ** [comment] 2019-06-24 19:53
I didn't have time to check, but thanks for taking care of this!
